 # =============================================================================
# DATA CONFIGURATION
# =============================================================================
# The datasets used in this repository are note included in this repo but are publicly available.
# 
# Instructions:
#FIX: add the directions to download the dataset
# 2. Update DATASET_PATH below to point to your file

# =============================================================================
from pathlib import Path

# Set repo and dataset filepaths
REPO_FILEPATH = Path("/discover/nobackup/hzafar/ghgc/micasa/FLUXNET-Model-comparison/")
DATA_FILEPATH = Path("/discover/nobackup/hzafar/ghgc/micasa/FLUXNET-Model-comparison/data/")

# Micasa data directory
MICASA_DATA_PATH = DATA_FILEPATH / "micasa-data"
# Micasa preprocessed data (generated by data-preprocessing.py)
MICASA_PREPROCESSED_DATA = REPO_FILEPATH / "preprocessing" / "intermediates"


# Flux data directory
FLUX_DATA_PATH = DATA_FILEPATH / "ameriflux-data/"
# Flux metadata file
FLUX_METADATA = FLUX_DATA_PATH / "AmeriFlux-site-search-results-202410071335.tsv"


