[project]
authors = ["Hannah Zafar <hannah.zafar@nasa.gov>"]
channels = ["conda-forge"]
description = "Kernel only for notebooks execution"
name = "notebooks"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
hvplot = ">=0.12.0,<0.13"
geoviews = ">=1.14.0,<2"
xarray = ">=2025.7.1,<2026"
matplotlib = ">=3.10.5,<4"
pandas = ">=2.3.1,<3"
ipykernel = ">=6.30.1,<7"
dask = ">=2025.7.0,<2026"
